# Generated by Django 6.0.7 on 2026-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_display',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
