# Generated by Django 6.0.7 on 2026-07-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_salary_job_salary_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(db_index=True, max_length=300)),
                ('location', models.CharField(default='', max_length=300)),
                ('description', models.TextField(default='')),
                ('source', models.CharField(default='', max_length=50)),
                ('posted_date', models.CharField(default='', max_length=200)),
                ('apply_url', models.URLField(default='')),
                ('search_query', models.CharField(default='', max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('salary_display', models.CharField(default='', max_length=50)),
                ('full_text', models.TextField(default='')),
                ('fetch_batch_id', models.CharField(db_index=True, default='', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('fetched', 'Fetched'), ('matched', 'Matched'), ('applied', 'Applied'), ('web_apply', 'Web Apply'), ('ignored', 'Ignored'), ('status_changed', 'Status Changed')], db_index=True, max_length=30)),
                ('old_status', models.CharField(default='', max_length=20)),
                ('new_status', models.CharField(default='', max_length=20)),
                ('match_score', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='first_seen_raw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_jobs', to='jobs.rawjob'),
        ),
    ]
