# Generated by Django 6.0.7 on 2026-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rawjob_job_updated_at_jobevent_job_first_seen_raw_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(default='', max_length=254)),
                ('encrypted_password', models.TextField(default='')),
                ('resume_file', models.FileField(blank=True, upload_to='resumes/')),
                ('resume_original_name', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credential Store',
                'verbose_name_plural': 'Credential Store',
            },
        ),
    ]
