# Generated by Django 6.0.7 on 2026-07-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_credstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('api_base_url', models.CharField(default='https://api.openai.com/v1', max_length=255)),
                ('encrypted_api_key', models.TextField(default='')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Config',
                'verbose_name_plural': 'AI Config',
            },
        ),
    ]
