# Generated by Django 6.0.7 on 2026-07-17 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_fetched', models.IntegerField(default=0)),
                ('total_matched', models.IntegerField(default=0)),
                ('total_applied', models.IntegerField(default=0)),
                ('total_ignored', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('top_keywords', models.JSONField(blank=True, default=list)),
                ('top_companies', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('posted_date', models.CharField(blank=True, default='', max_length=200)),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('matched', 'Matched'), ('applied', 'Applied'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='new', max_length=20)),
                ('apply_email', models.EmailField(blank=True, default='', max_length=254)),
                ('apply_url', models.URLField(blank=True, default='')),
                ('search_query', models.CharField(blank=True, default='', max_length=200)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('skill_score_breakdown', models.JSONField(blank=True, default=dict)),
                ('job_url', models.URLField(blank=True, default='')),
                ('uid', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'ordering': ['-match_score', '-fetched_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_subject', models.CharField(blank=True, default='', max_length=500)),
                ('cover_letter_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('skills_highlighted', models.JSONField(blank=True, default=list)),
                ('skills_in_job_desc', models.JSONField(blank=True, default=list)),
                ('skill_match_pct', models.FloatField(default=0)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='dashboard.job')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('found_in_job_desc', models.BooleanField(default=False)),
                ('highlighted_in_cover_letter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_logs', to='dashboard.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_logs', to='dashboard.job')),
            ],
        ),
    ]
