# Generated by Django 6.0.7 on 2026-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='criteria_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='match_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='skill_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='filter_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='match_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
