# Generated by Django 6.0.7 on 2026-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_application_criteria_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('web_apply', 'Web Apply')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('matched', 'Matched'), ('applied', 'Applied'), ('web_apply', 'Web Apply'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
